### ISSUE TITLE
Upload files and Python2 vs Python3

### ISSUE THREAD

**Issue by LuisSoares** [genepattern/genepattern-python#3]
This is actually a two issue issue. First in Python3 it seems that gpserver.auth_header returns None, this make it impossible to submit jobs that require the authorization header. Second I am unable to upload files programatically (even trying to reproduce the tutorial) I get an authorization failed when trying to upload files, this is just the exception catching print, further digging using the urlib request I found that the response code was 307, temporary moved. Any suggestions?

**Comment by tmtabor** [comment]
Since you closed the ticket, I will assume this has been solved.
