### ISSUE TITLE
Unclosed file warning

### ISSUE THREAD

**Issue by GeorgesBed** [genepattern/genepattern-python#4]
Hello developers team,
i have been using the gene pattern python library recently to retrieve the ESPpredictor score for some peptide sequences. It is a great and helpful tool.
However, I am getting the following unharmful warning: 
 
     test_indel_fs_treatement (__main__.TestAll_g2p) ... D:\tools\Python3\lib\site-packages\gp\core.py:55: ResourceWarning: unclosed file <_io.BufferedReader name='./ESPredictor_pepSeq'>
     data = open(file_path, 'rb').read()

since the file handle is not closed.
Thank you :)

**Comment by tmtabor** [comment]
Good catch! We're going to put out a new release at the end of the week and I'll make sure this bug gets fixed in it.

**Comment by tmtabor** [comment]
Fixed in [this commit](https://github.com/genepattern/genepattern-python/commit/b8c496d6c841288eddbb4f9becb442d8873fc6c7).
